### ISSUE TITLE
Permission to take over

### ISSUE THREAD

**Issue by AndrewJWin** [ttgc/FactCore#2]
My name is Andrew()#9999 on discord, I am the owner and creator of your partner bot **GLadOS#5082**.

I'm attaching this "Issue" to post a request;

**Allow me to take over FactCore**.

I will rewrite him in Javascript, and host him permanently beside GLadOS.

The original owner will still have full permissions to change any portion of the bot as they desire, however I will remain the developer and host of the bot.

Please give this some thought and let me know on Discord.

**Comment by VicenteX01** [comment]
Ok, that's good! Thank you for recontinuing the bot! :3 (Now I wish I could make more Personality Core Discord Bots, but I don't know anything about bot coding. Lol.)

**Comment by ttgc** [comment]
The bot won't be changed by myself from now. @AndrewJWin is now the new developer of the bot,
